import { TelegramClient } from "telegram";
import { StringSession } from "telegram/sessions/index.js";
import { env } from "../../config/env.js";

/**
 * Foundation for the future Telegram/MTProto storage backend.
 *
 * This module is intentionally limited to configuration + connection
 * lifecycle. It does NOT implement upload, download, chunking, or any
 * storage-channel file operations — that's the next phase. What's
 * here lets that phase start from a working, already-authenticated
 * client instead of wiring GramJS from scratch.
 *
 * How the session is meant to work:
 *   1. TELEGRAM_API_ID / TELEGRAM_API_HASH come from https://my.telegram.org
 *   2. TELEGRAM_SESSION_STRING is produced once, out-of-band, by
 *      logging in interactively with GramJS's StringSession and
 *      printing session.save() — never generated by the server itself
 *      on every boot.
 *   3. TELEGRAM_STORAGE_CHANNEL_ID is the private channel this backend
 *      will use as a storage bucket in the next phase.
 */

let client = null;
let connecting = null;

export function isTelegramConfigured() {
  return Boolean(env.TELEGRAM_API_ID && env.TELEGRAM_API_HASH && env.TELEGRAM_SESSION_STRING);
}

export function getTelegramConfigStatus() {
  return {
    apiIdSet: Boolean(env.TELEGRAM_API_ID),
    apiHashSet: Boolean(env.TELEGRAM_API_HASH),
    sessionSet: Boolean(env.TELEGRAM_SESSION_STRING),
    storageChannelSet: Boolean(env.TELEGRAM_STORAGE_CHANNEL_ID),
    ready: isTelegramConfigured(),
  };
}

/**
 * Lazily creates and connects a single shared TelegramClient. Returns
 * null (rather than throwing) when Telegram isn't configured yet, so
 * the rest of the app can boot and run auth without it — Telegram
 * storage is a later phase, not a hard dependency of this one.
 */
export async function getTelegramClient() {
  if (!isTelegramConfigured()) {
    return null;
  }

  if (client) {
    return client;
  }

  if (!connecting) {
    connecting = (async () => {
      const session = new StringSession(env.TELEGRAM_SESSION_STRING);
      const newClient = new TelegramClient(
        session,
        Number.parseInt(env.TELEGRAM_API_ID, 10),
        env.TELEGRAM_API_HASH,
        {
          connectionRetries: env.TELEGRAM_CONNECTION_RETRIES,
        }
      );
      await newClient.connect();
      client = newClient;
      return client;
    })();
  }

  return connecting;
}

export async function disconnectTelegramClient() {
  if (client) {
    await client.disconnect();
    client = null;
    connecting = null;
  }
}
